version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: myclinicpay
      MONGO_INITDB_ROOT_USERNAME: lgaricoix
      MONGO_INITDB_ROOT_PASSWORD: 010133
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
  my-clinic-pay:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-clinic-pay:latest
    ports:
      - 8082:8082
