version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: myclinicpay
    environment:
      MONGO_INITDB_DATABASE: myclinicpay
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 010133
    ports:
      - 27017:27017
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - ./mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8087:8087
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 010133
