server:
  port: ${PORT:8082}

spring:
  data:
    mongodb:
      uri: "mongodb+srv://lgaricoix:010133@cluster0.42jwu.mongodb.net/?retryWrites=true&w=majority"

jwt:
  secret: "m7jaa6IQZyx2PSHOEs3JF6c31TMobW264WrTObnrXyc="

encrypt:
  secret: "78fc2a3b-cf95-4306-8c60-8e63195d8625"
  salt: "${$AX,2_esL7#^JY"
