name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: sa_east_1

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - run: ./gradlew build -x check

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

  deploy:
    name: Deploy to Digitalocean Droplet
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Copy artifact via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          source: "build/libs"
          target: "artifact"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          script: cd server |
            chmod +x run.sh |
            ./run.sh
